---
# Requirements file para las colecciones de Ansible necesarias
# para el proyecto Azure Service Plan Auto Scaler

collections:
  # Colección oficial de Azure para Ansible
  - name: azure.azcollection
    version: ">=2.0.0"
    source: https://galaxy.ansible.com

  # Colección para funcionalidades adicionales de Ansible
  - name: ansible.posix
    version: ">=1.5.0" 
    source: https://galaxy.ansible.com

  # Colección para utilidades de comunidad
  - name: community.general
    version: ">=6.0.0"
    source: https://galaxy.ansible.com