# Azure Dynamic Inventory Configuration
# Plugin: azure.azcollection.azure_rm
# Documentación: https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_inventory.html

plugin: azure.azcollection.azure_rm

# Incluir recursos de todos los Resource Groups
include_vm_resource_groups:
  - "*"

# Autenticación (AWX usará las credenciales configuradas)
# No es necesario especificar aquí, AWX inyecta:
# - AZURE_CLIENT_ID
# - AZURE_SECRET
# - AZURE_SUBSCRIPTION_ID
# - AZURE_TENANT

# Filtros de recursos
exclude_host_filters:
  - powerstate != 'running'

# Agrupar por diferentes atributos
keyed_groups:
  # Agrupar por Resource Group
  - key: resource_group
    prefix: rg
    separator: "_"
  
  # Agrupar por ubicación
  - key: location
    prefix: location
    separator: "_"
  
  # Agrupar por tipo de OS
  - key: os_disk.operating_system_type
    prefix: os
    separator: "_"
  
  # Agrupar por tags
  - key: tags
    prefix: tag
    separator: "_"

# Variables de host desde propiedades de Azure
hostvar_expressions:
  # IP pública (si existe)
  ansible_host: public_ipv4_addresses[0] if public_ipv4_addresses else private_ipv4_addresses[0]
  
  # Información del recurso
  azure_vm_size: vm_size
  azure_location: location
  azure_resource_group: resource_group
  azure_os_type: os_disk.operating_system_type
  azure_tags: tags
  
  # Información de red
  azure_public_ip: public_ipv4_addresses[0] if public_ipv4_addresses else None
  azure_private_ip: private_ipv4_addresses[0] if private_ipv4_addresses else None

# Grupos condicionales
conditional_groups:
  # VMs Windows
  windows: "'windows' in os_disk.operating_system_type.lower()"
  
  # VMs Linux
  linux: "'linux' in os_disk.operating_system_type.lower()"
  
  # VMs en ejecución
  running: "powerstate == 'running'"
  
  # VMs detenidas
  stopped: "powerstate != 'running'"

# Usar cache (mejora rendimiento)
cache: yes
cache_plugin: jsonfile
cache_timeout: 1800  # 30 minutos
cache_connection: /tmp/ansible_azure_inventory_cache
cache_prefix: azure_rm

# Logging
#debug: yes
