---
- name: Listar App Service Plans de Azure
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: Obtener todos los App Service Plans
      azure.azcollection.azure_rm_appserviceplan_info:
      register: service_plans
      
    - name: Mostrar resumen de App Service Plans
      debug:
        msg: |
          === APP SERVICE PLANS ENCONTRADOS ===
          Total: {{ service_plans.appserviceplans | length }}
    
    - name: Mostrar detalles de cada App Service Plan
      debug:
        msg: |
          📋 Nombre: {{ item.name }}
          🏷️  Resource Group: {{ item.resource_group }}
          📍 Ubicación: {{ item.location }}
          💰 Tier actual: {{ item.sku.tier }}
          📊 Tamaño: {{ item.sku.name }}
          🔢 Capacidad: {{ item.sku.capacity }}
          {% if item.sku.tier == 'Free' %}
          💡 Estado: GRATIS (F1)
          {% elif item.sku.tier == 'Basic' %}
          💸 Estado: BÁSICO (B1)
          {% else %}
          🚀 Estado: {{ item.sku.tier }}
          {% endif %}
      loop: "{{ service_plans.appserviceplans }}"
      loop_control:
        label: "{{ item.name }}"
    
    - name: Crear reporte de Service Plans
      copy:
        content: |
          # App Service Plans Report
          Generado: {{ ansible_date_time.iso8601 }}
          
          {% for sp in service_plans.appserviceplans %}
          ## {{ sp.name }}
          - Resource Group: {{ sp.resource_group }}
          - Location: {{ sp.location }}
          - Tier: {{ sp.sku.tier }}
          - Size: {{ sp.sku.name }}
          - Capacity: {{ sp.sku.capacity }}
          - ID: {{ sp.id }}
          
          {% endfor %}
          
          Total Service Plans: {{ service_plans.appserviceplans | length }}
        dest: "/tmp/azure_service_plans_{{ ansible_date_time.epoch }}.txt"
    
    - name: Identificar Service Plans candidatos para scaling
      set_fact:
        scalable_plans: "{{ service_plans.appserviceplans | selectattr('sku.tier', 'in', ['Free', 'Basic']) | list }}"
    
    - name: Mostrar Service Plans que pueden escalarse
      debug:
        msg: |
          🎯 SERVICE PLANS PARA AUTOMATIZACIÓN:
          
          {% if scalable_plans | length > 0 %}
          {% for sp in scalable_plans %}
          ✅ {{ sp.name }} ({{ sp.resource_group }})
             Tier actual: {{ sp.sku.tier }} ({{ sp.sku.name }})
             {% if sp.sku.tier == 'Free' %}
             ⬆️  Puede escalarse a: B1 (Basic)
             {% else %}
             ⬇️  Puede reducirse a: F1 (Free)
             {% endif %}
          {% endfor %}
          
          💡 Total escalables: {{ scalable_plans | length }}
          {% else %}
          ⚠️  No se encontraron Service Plans con tier Free o Basic
          {% endif %}