---
- name: Automatización Sencilla - Información del Sistema (Simple)
  hosts: all
  gather_facts: yes
  tasks:
    - name: Mostrar información del hostname
      debug:
        msg: "Hostname: {{ inventory_hostname }}"
    
    - name: Mostrar información del sistema operativo
      debug:
        msg: "SO: {{ ansible_distribution | default('Unknown') }} {{ ansible_distribution_version | default('Unknown') }}"
    
    - name: Mostrar información de la fecha
      debug:
        msg: "Fecha: {{ ansible_date_time.date }} - Hora: {{ ansible_date_time.time }}"
    
    - name: Verificar conectividad
      ping:
    
    - name: Crear archivo de ejemplo
      copy:
        content: |
          Archivo creado automáticamente por AWX
          Fecha: {{ ansible_date_time.date }}
          Hora: {{ ansible_date_time.time }}
          Servidor: {{ inventory_hostname }}
          Sistema: {{ ansible_distribution | default('Unknown') }}
        dest: /tmp/awx_automation_test.txt
        mode: '0644'
      become: yes
      ignore_errors: yes
    
    - name: Verificar que el archivo se creó
      stat:
        path: /tmp/awx_automation_test.txt
      register: archivo_creado
      
    - name: Mostrar resultado de creación de archivo
      debug:
        msg: "{{ 'Archivo creado exitosamente' if archivo_creado.stat.exists else 'Error al crear archivo' }}"